# Generated by Django 3.0 on 2019-12-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191206_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
